"use client";
import {useEffect,useState} from "react";
import {BarChart3,CheckCircle2,ShieldCheck,Users,Vote,Info} from "lucide-react";
import {supabase} from "@/lib/supabase";
type Candidate={id:string;name:string;party:string;image:string};
const candidates:Candidate[]=[
{id:"ranganath",name:"A. P. Ranganath",party:"NDA",image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYUM_XlRGSDZomXWxorY6KhocpOa5hMIpXw63Th658L3CJ4Nqw6xbrRoQ&s=10"},
{id:"puttanna",name:"Puttanna",party:"Congress",image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmoVM6i0rksnMOkzst_cCClC8WDYEArPnanR2hMDLHapIJ5mWikAifLtno&s=10"}];
export default function Home(){
const [selected,setSelected]=useState("");const [counts,setCounts]=useState<Record<string,number>>({ranganath:0,puttanna:0});const [total,setTotal]=useState(0);const [submitted,setSubmitted]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
async function loadResults(){const {data,error}=await supabase().from("poll_results").select("candidate_id,vote_count");if(!error&&data){const c={ranganath:0,puttanna:0};data.forEach((r:{candidate_id:string;vote_count:number})=>{if(r.candidate_id in c)c[r.candidate_id as keyof typeof c]=Number(r.vote_count)||0});setCounts(c);setTotal(c.ranganath+c.puttanna)}setLoading(false)}
useEffect(()=>{loadResults();setSubmitted(localStorage.getItem("poll_submitted")==="1")},[]);
async function vote(){if(!selected||submitted)return;setMessage("");const voterId=localStorage.getItem("poll_voter_id")||crypto.randomUUID();localStorage.setItem("poll_voter_id",voterId);const {error}=await supabase().from("votes").insert({candidate_id:selected,voter_id:voterId});if(error){setMessage(error.code==="23505"?"A response has already been recorded on this browser.":"We couldn't record your response. Please try again.");return}localStorage.setItem("poll_submitted","1");setSubmitted(true);setMessage("Your response has been recorded anonymously.");await loadResults()}
return <main>
<header className="topbar"><div className="brand"><div className="brandmark"><Vote size={21}/></div><div><strong>Public Opinion Poll</strong><span>Academic survey • 2026</span></div></div><a href="#method">How it works</a></header>
<section className="hero"><div className="eyebrow">BENGALURU TEACHERS’ CONSTITUENCY</div><h1>Who would you choose?</h1><p>This independent, anonymous survey is being conducted for academic purposes. Select one candidate based on your own view.</p><div className="notice"><Info size={18}/><span>This is an opinion survey, not an official election ballot or an Election Commission poll.</span></div></section>
<section className="poll-card"><div className="section-head"><div><h2>Your response</h2><p>Choose one option</p></div><div className="live"><span/>Live results</div></div>
<div className="candidates">{candidates.map(c=><button key={c.id} className={"candidate "+(selected===c.id?"selected":"")} onClick={()=>!submitted&&setSelected(c.id)} disabled={submitted}><img src={c.image} alt={c.name}/><div className="candidate-copy"><span className="candidate-party">{c.party}</span><strong>{c.name}</strong><span className="radio">{selected===c.id?"✓":""}</span></div></button>)}</div>
<button className="submit" disabled={!selected||submitted} onClick={vote}>{submitted?<><CheckCircle2 size={19}/> Response recorded</>:<><Vote size={19}/> Submit my response</>}</button>{message&&<p className="message"><CheckCircle2 size={17}/>{message}</p>}</section>
<section className="results-card"><div className="section-head"><div><h2>Survey results</h2><p>Responses recorded so far</p></div><BarChart3 size={22}/></div>{loading?<div className="skeleton"/>:<div className="results">{candidates.map(c=>{const n=counts[c.id]||0;const pct=total?Math.round(n/total*100):0;return <div className="result" key={c.id}><div className="result-top"><span>{c.name}</span><strong>{pct}%</strong></div><div className="bar"><i style={{width:pct+"%"}}/></div></div>})}<div className="total"><Users size={18}/><strong>{total}</strong><span>total responses</span></div></div>}</section>
<section id="method" className="method"><div className="method-item"><ShieldCheck/><div><strong>Anonymous by design</strong><p>No name, phone number or email is requested for voting.</p></div></div><div className="method-item"><Users/><div><strong>One response per browser</strong><p>The browser identifier only reduces duplicate submissions; it cannot guarantee one response per person.</p></div></div><div className="method-item"><Info/><div><strong>Academic use</strong><p>Results describe this survey sample only and should not be presented as a prediction of the official election result.</p></div></div></section>
<footer>Independent academic opinion survey • Bengaluru • 2026</footer></main>}